paths:
    - manifest: "resources/AndroidManifest.xml"
    - strings: "resources/res/values/strings.xml"
# These are the regex patterns that you can modify.
patterns:
    URLS: 
        - regex: "https?://[^\"\\'> ]+"
    AwsKeys: 
        - regex: "([^A-Z0-9]|^)(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}"
    firebaseURL: 
        - regex: "*.firebaseio.com"
